[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && npm install --build-from-source"
]

[start]
cmd = "cd backend && node src/app.js"
