[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["cd backend && npm install --build-from-source"]

[start]
cmd = "cd backend && node src/db/seed.js; node src/app.js"
